version: "3.9"
services:
  curl:
    image: curlimages/curl:7.75.0
    command: /entrypoint.sh
    environment:
      PROXY_URL: http://proxy:8888
      HTTP_URL: http://nginx/index.html
      HTTPS_URL: https://nginx/index.html
    volumes:
      - "./curl/entrypoint.sh:/entrypoint.sh:ro"
  proxy:
    image: vimagick/tinyproxy:latest
  nginx:
    image: nginx:1.19.6
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/cert.pem:/etc/nginx/cert.pem:ro"
      - "./nginx/key.pem:/etc/nginx/key.pem:ro"
